name: Maven deploy

on:
  workflow_dispatch:
    inputs:
      maven_command:
        required: false
        type: string
        default: "--batch-mode deploy"
permissions:
  packages: write
jobs:
  mvn:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Display settings.xml
        run: cat ~/.m2/settings.xml         
      - name: "Maven deploy"
        run: |
          mvn --batch-mode deploy -Dgpg.skip=true -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
