name: Scout repository scan
on:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  anchore:
    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        continue-on-error: true
        with:
          command: cves
          image: fs://../${{ github.event.repository.name }}
          sarif-file: sarif.output.json
          summary: true
          ignore-base: true
          dockerhub-user: ${{ secrets.DOCKER_IO_USER }}
          dockerhub-password: ${{ secrets.DOCKER_IO_PASSWORD }}
